# Generated by Django 4.2.4 on 2023-08-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True)),
                ('team_name', models.TextField()),
                ('total_team_members', models.IntegerField()),
                ('leader_name', models.TextField()),
                ('leader_university', models.TextField()),
                ('leader_major', models.TextField()),
                ('leader_whatsapp_number', models.TextField()),
                ('leader_email', models.EmailField(max_length=254)),
                ('Leader_address', models.TextField()),
                ('leader_student_id', models.ImageField(upload_to='')),
                ('leader_active_student_proof', models.ImageField(upload_to='')),
                ('leader_3x4_photo', models.ImageField(upload_to='')),
                ('member_1_name', models.TextField()),
                ('member_1_university', models.TextField()),
                ('member_1_major', models.TextField()),
                ('member_1_whatsapp_number', models.TextField()),
                ('member_1_email', models.EmailField(max_length=254)),
                ('member_1_address', models.TextField()),
                ('member_1_student_id', models.ImageField(upload_to='')),
                ('member_1_active_student_proof', models.ImageField(upload_to='')),
                ('member_1_3x4_photo', models.ImageField(upload_to='')),
                ('member_2_name', models.TextField()),
                ('member_2_university', models.TextField()),
                ('member_2_major', models.TextField()),
                ('member_2_whatsapp_number', models.TextField()),
                ('member_2_email', models.EmailField(max_length=254)),
                ('member_2_address', models.TextField()),
                ('member_2_student_id', models.ImageField(upload_to='')),
                ('member_2_active_student_proof', models.ImageField(upload_to='')),
                ('member_2_3x4_photo', models.ImageField(upload_to='')),
                ('member_3_name', models.TextField()),
                ('member_3_university', models.TextField()),
                ('member_3_major', models.TextField()),
                ('member_3_whatsapp_number', models.TextField()),
                ('member_3_email', models.EmailField(max_length=254)),
                ('member_3_address', models.TextField()),
                ('member_3_student_id', models.ImageField(upload_to='')),
                ('member_3_active_student_proof', models.ImageField(upload_to='')),
                ('member_3_3x4_photo', models.ImageField(upload_to='')),
                ('payment_total', models.IntegerField()),
                ('referral_code', models.TextField()),
                ('payment_methods', models.TextField()),
                ('payment_proof', models.ImageField(upload_to='')),
            ],
        ),
    ]
