# Generated by Django 4.2.4 on 2023-09-04 02:57

from django.db import migrations, models
import django.db.models.deletion
import register.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(unique=True, verbose_name='Competition')),
                ('min_capacity', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(verbose_name='Kode Referral')),
                ('is_redeemed', models.BooleanField(verbose_name='Sudah digunakan? (Ceklis berarti sudah)')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('team_name', models.CharField(unique=True)),
                ('total_team_members', models.IntegerField(default=0, editable=False)),
                ('payment_total', models.IntegerField(verbose_name='Total Pembayaran')),
                ('referral_code', models.CharField(blank=True, verbose_name='Kode Referral')),
                ('payment_methods', models.CharField(verbose_name='Metode Pembayaran')),
                ('payment_proof', models.ImageField(upload_to=register.models.Team.upload_payment, verbose_name='Bukti foto pembayaran')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.competition', verbose_name='Cabang lomba')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(verbose_name='Nama')),
                ('role', models.CharField(choices=[('LEADER', 'Leader'), ('MEMBER', 'Member')], default='LEADER', verbose_name='Role')),
                ('university', models.CharField(verbose_name='Universitas')),
                ('major', models.CharField(verbose_name='Jurusan')),
                ('whatsapp_number', models.CharField(verbose_name='Nomor WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(verbose_name='Alamat')),
                ('student_id', models.ImageField(upload_to=register.models.Member.upload_photo_id, verbose_name='Foto KTM')),
                ('active_student_proof', models.ImageField(upload_to=register.models.Member.upload_photo_proof, verbose_name='Bukti Foto Mahasiswa Aktif')),
                ('photo_3x4', models.ImageField(upload_to=register.models.Member.upload_photo_3x4, verbose_name='Foto 3x4')),
                ('photo_twibbon', models.ImageField(upload_to=register.models.Member.upload_photo_twibbon, verbose_name='Foto Twibbon')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.team')),
            ],
        ),
    ]
