# Generated by Django 4.2.4 on 2023-08-26 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tim',
            new_name='Team',
        ),
    ]
