# Generated by Django 4.2.4 on 2023-09-11 15:05

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo_follow_ig',
            field=models.ImageField(blank=True, null=True, upload_to=register.models.Member.upload_photo_follow_instagram, verbose_name='Bukti Follow Instagram ICEE ITB'),
        ),
    ]
