# Generated by Django 4.2.4 on 2023-08-26 02:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_tim_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='Leader_address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_major',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_university',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_whatsapp_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_1_address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_1_major',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_1_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_1_university',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_1_whatsapp_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_2_address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_2_major',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_2_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_2_university',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_2_whatsapp_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_3_address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_3_major',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_3_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_3_university',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_3_whatsapp_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='payment_methods',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='referral_code',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
