# Generated by Django 4.2.4 on 2023-09-22 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_member_photo_follow_ig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcode',
            name='is_redeemed',
        ),
        migrations.AddField(
            model_name='referralcode',
            name='competition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='register.competition'),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='times_used',
            field=models.IntegerField(default=0, verbose_name='Sudah berapa kali digunakan?'),
        ),
    ]
